### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by dpriskorn** [magnusmanske/cersei#2]
Shouldn't this 
https://github.com/magnusmanske/cersei/blob/b5350497f05a227f9bfc158fb7c5e3aa1511679f/src/values.py#L74
be
`if letter not in self.LETTER_TO_TYPE:`

**Comment by dpriskorn** [comment]
Anyway, if you use Enums it looks something like this:
```
class WikidataNamespaceLetters(Enum):
		PROPERTY="P"
		ITEM="Q"
                LEXEME="L"

	def __init__(self, q: str = None):
		super().__init__()
		q = q.strip().upper()
		if length(q) < 2:
			raise Exception("ItemValue: "+q+" is too short")
		# see https://towardsdatascience.com/python-power-tip-enumerated-types-9a1e606250a4 under Type Conversions
		self.item_type = WikidataNamespaceLetters[q[0)] # this throws a meaningful exception if it cannot be converted
		number_string = str(q[1:])
		if not number_string.isnumeric():
			raise Exception("ItemValue: "+number_string+" is not numeric")
		self.item_id = int(number_string)
```

**Comment by dpriskorn** [comment]
Also consider renaming the "item_id" to entity_number or something which is more generic and less confusing. :)

**Comment by dpriskorn** [comment]
See my Wikidata classes here, inspired by yours :) 
https://github.com/dpriskorn/LexODS/blob/master/models/wikidata.py (untested code)

**Comment by magnusmanske** [comment]
Went with enums as per #1
