### ISSUE TITLE
Error in requirements.txt?

### ISSUE THREAD

**Issue by dpriskorn** [magnusmanske/cersei#3]
Collecting attrs==21.2.0
  Downloading attrs-21.2.0-py2.py3-none-any.whl (53 kB)
Collecting Automat==20.2.0
  Downloading Automat-20.2.0-py2.py3-none-any.whl (31 kB)
Collecting beautifulsoup4==4.9.1
  Downloading beautifulsoup4-4.9.1-py3-none-any.whl (115 kB)
Collecting certifi==2021.5.30
  Using cached certifi-2021.5.30-py2.py3-none-any.whl (145 kB)
Collecting cffi==1.14.6
  Downloading cffi-1.14.6-cp38-cp38-win_amd64.whl (179 kB)
Collecting chardet==4.0.0
  Using cached chardet-4.0.0-py2.py3-none-any.whl (178 kB)
Collecting constantly==15.1.0
  Downloading constantly-15.1.0-py2.py3-none-any.whl (7.9 kB)
Collecting cryptography==3.2.1
  Downloading cryptography-3.2.1-cp38-cp38-win_amd64.whl (1.5 MB)
Collecting cssselect==1.1.0
  Downloading cssselect-1.1.0-py2.py3-none-any.whl (16 kB)
Collecting hyperlink==21.0.0
  Downloading hyperlink-21.0.0-py2.py3-none-any.whl (74 kB)
Collecting idna==2.10
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting incremental==21.3.0
  Downloading incremental-21.3.0-py2.py3-none-any.whl (15 kB)
Collecting itemadapter==0.1.0
  Downloading itemadapter-0.1.0-py3-none-any.whl (7.0 kB)
Collecting itemloaders==1.0.3
  Downloading itemloaders-1.0.3-py3-none-any.whl (11 kB)
Collecting jmespath==0.10.0
  Downloading jmespath-0.10.0-py2.py3-none-any.whl (24 kB)
Collecting lxml==4.6.3
  Using cached lxml-4.6.3-cp38-cp38-win_amd64.whl (3.5 MB)
Collecting parsel==1.6.0
  Downloading parsel-1.6.0-py2.py3-none-any.whl (13 kB)

ERROR: Could not find a version that satisfies the requirement pkg-resources==0.0.0 (from versions: none)
ERROR: No matching distribution found for pkg-resources==0.0.0

![bild](https://user-images.githubusercontent.com/68460690/128372386-606b0e6c-a3cf-4417-9458-790372944345.png)

**Comment by dpriskorn** [comment]
see also https://github.com/SkalskiP/ILearnDeepLearning.py/issues/8
I'm on Win10 with PyCharm a little old
![bild](https://user-images.githubusercontent.com/68460690/128372827-6f2d154e-fe25-4f44-8e0f-049d107807bc.png)

**Comment by magnusmanske** [comment]
Removed.

I have seen this before, not sure why pip freeze adds that sometimes.
